import test from 'node:test';
import assert from 'node:assert/strict';
import { createChatState } from '../src/core/chat-state.js';
import { reviewSummary } from '../src/ui/presentation.js';
import { productionReviewState } from './helpers/production-fixtures.js';
import { mountFushengluApp } from '../src/ui/app.js';
import { createDomApp, flush } from './helpers/dom-environment.js';

const time = '2026-08-01T00:00:00.000Z';
test('confirms a review batch through mounted DOM', async () => {
  let state = createChatState(time);
  const fixture = productionReviewState(state); state = fixture.state;
  assert.deepEqual(fixture.classified.map((x) => x.disposition), ['apply', 'apply', 'pending']); assert.equal(fixture.batch.detectedChanges.length, 2); assert.equal(fixture.batch.uncertainItems.length, 1);
  const env = createDomApp(new Map([['chat:one', state]]));
  const app = mountFushengluApp({ store: env.store, settingsStore: env.settingsStore, apiClient: {}, documentRef: env.document });
  app.root.querySelector('.fushenglu-entry').click(); await flush(); app.root.querySelector('[data-nav="review"]').click();
  assert.equal(app.root.querySelectorAll('.fushenglu-change').length, 2); const button = app.root.querySelector('[data-action="confirm-batch"]'); assert.ok(button); button.click(); button.click(); await flush(); await flush();
  const saved = await env.store.read(); assert.equal(saved.state.committedBatchIds.length, 1); assert.equal(saved.state.eventLedger.eventIds.length, 2); assert.equal(saved.state.currentSnapshot.currentTime, '三月十八申時'); assert.equal(saved.state.currentSnapshot.currentPlace, '藏書閣'); assert.equal(app.root.querySelector('[data-action="confirm-batch"]'), null); assert.match(app.root.querySelector('.fushenglu-global-status').textContent, /已更新浮生錄/); assert.equal(saved.state.pendingItems.length, 1); app.destroy(); env.destroy();
});
test('resets the active chat through mounted DOM', async () => {
  let state = createChatState(time); state.worldRules.entries.push({ schemaVersion: 1, ruleKey: 'r', type: 'x', description: 'x', status: 'confirmed' }); state.events.push({ schemaVersion: 1, eventId: 'e', kind: 'story_time', operation: 'set', value: { time: '今日' }, sourceMessageRefs: [], deletedAt: null, updatedAt: time });
  const other = createChatState(time); other.events.push({ ...state.events[0], eventId: 'other' }); const env = createDomApp(new Map([['chat:one', state], ['chat:two', other]])); const app = mountFushengluApp({ store: env.store, settingsStore: env.settingsStore, apiClient: {}, documentRef: env.document }); app.root.querySelector('.fushenglu-entry').click(); await flush(); app.root.querySelector('[data-nav="settings"]').click(); app.root.querySelector('[data-action="open-reset"]').click(); assert.equal((await env.store.read()).state.events.length, 1); assert.ok(app.root.querySelector('[data-reset-dialog]')); app.root.querySelector('[data-action="confirm-reset"]').click(); await flush(); const reset = (await env.store.read()).state; assert.equal(reset.events.length, 0); assert.equal(reset.worldRules.entries.length, 1); env.switchChat('chat:two'); await flush(); assert.equal((await env.store.read()).state.events.length, 1); app.destroy(); env.destroy();
});
test('keeps reset dialog and data on metadata save failure through mounted DOM', async () => { const state = createChatState(time); state.events.push({ schemaVersion: 1, eventId: 'e', kind: 'story_time', operation: 'set', value: { time: '今日' }, sourceMessageRefs: [], deletedAt: null, updatedAt: time }); const env = createDomApp(new Map([['chat:one', state], ['chat:two', createChatState(time)]])); const app = mountFushengluApp({ store: env.store, settingsStore: env.settingsStore, apiClient: {}, documentRef: env.document }); app.root.querySelector('.fushenglu-entry').click(); await flush(); app.root.querySelector('[data-nav="settings"]').click(); app.root.querySelector('[data-action="open-reset"]').click(); env.failSave = true; app.root.querySelector('[data-action="confirm-reset"]').click(); await flush(); assert.ok(app.root.querySelector('[data-reset-dialog]')); assert.equal((await env.store.read()).state.events.length, 1); assert.match(app.root.querySelector('.fushenglu-global-status').textContent, /保存失敗/); env.failSave = false; app.root.querySelector('[data-action="confirm-reset"]').click(); await flush(); assert.equal((await env.store.read()).state.events.length, 0); app.destroy(); env.destroy(); });
test('saves confirmation mode through mounted DOM', async () => { const env = createDomApp(new Map([['chat:one', createChatState(time)]])); const app = mountFushengluApp({ store: env.store, settingsStore: env.settingsStore, apiClient: {}, documentRef: env.document }); app.root.querySelector('.fushenglu-entry').click(); await flush(); app.root.querySelector('[data-nav="settings"]').click(); const select = app.root.querySelector('[data-confirmation-mode]'); assert.equal(select.value, 'review_once'); select.value = 'auto_commit_safe'; app.root.querySelector('[data-action="save-confirmation-mode"]').click(); await flush(); assert.equal(env.settingsStore.load().confirmationMode, 'auto_commit_safe'); app.destroy(); env.destroy(); });

test('progressively renders pending cards through mounted DOM', async () => { const state = createChatState(time); state.pendingItems = Array.from({ length: 162 }, (_, i) => ({ schemaVersion: 1, pendingId: `p${i}`, status: 'pending', proposal: { value: { name: `<項目${i}>` } }, decisionHistory: [] })); state.pendingItems.push({ schemaVersion: 1, pendingId: 'done', status: 'accepted', proposal: { value: { name: '已處理' } }, decisionHistory: [] }); const env = createDomApp(new Map([['chat:one', state], ['chat:two', state]])); const app = mountFushengluApp({ store: env.store, settingsStore: env.settingsStore, apiClient: {}, documentRef: env.document }); app.root.querySelector('.fushenglu-entry').click(); await flush(); app.root.querySelector('[data-nav="pending"]').click(); assert.equal(app.root.querySelectorAll('article[data-pending-id]').length, 20); app.root.querySelector('[data-action="show-more-pending"]').click(); assert.equal(app.root.querySelectorAll('article[data-pending-id]').length, 40); env.switchChat('chat:two'); await flush(); app.root.querySelector('[data-nav="pending"]').click(); assert.equal(app.root.querySelectorAll('article[data-pending-id]').length, 20); app.destroy(); env.destroy(); });

test('mounts a V5 chat after resetting only malformed history progress', async () => { const state = createChatState(time); state.historyImportProgress = { schemaVersion: 1, completedChunks: [0] }; const env = createDomApp(new Map([['chat:one', state]])); const app = mountFushengluApp({ store: env.store, settingsStore: env.settingsStore, apiClient: {}, documentRef: env.document }); app.root.querySelector('.fushenglu-entry').click(); await flush(); const saved = await env.store.read(); assert.deepEqual(saved.state.historyImportProgress.completedChunkIndexes, []); assert.equal(saved.state.historyImportProgress.failedChunkIndex, null); assert.ok(app.root.querySelector('[data-nav="home"]')); assert.notEqual(app.root.textContent.trim(), ''); app.destroy(); env.destroy(); });
