const NON_MAIN = new Set(['memory', 'quote', 'dream', 'hypothetical', 'hearsay', 'plan', 'unknown']);
const OWNERSHIP = new Set(['owned','gifted','purchased','borrowed','temporary','custody','stored','unknown']);
const CONTAINERS = new Set(['carried','inventory','sleeve','storage_space','room','other']);
function clone(value) { return typeof structuredClone === 'function' ? structuredClone(value) : JSON.parse(JSON.stringify(value)); }
function text(value) { const result = String(value ?? '').trim(); return result || null; }
function source(event) { return event.sourceOrder ?? { messageIndex: Number(event.sourceMessageIndex) || 0, evidenceOrder: 0 }; }
function order(left, right) { const a = source(left); const b = source(right); return a.messageIndex - b.messageIndex || a.evidenceOrder - b.evidenceOrder || String(left.eventId).localeCompare(String(right.eventId)); }
function quantity(value) { const raw = value?.quantity; if (raw && typeof raw === 'object') return { exact: Number.isFinite(raw.exact) ? raw.exact : null, unit: text(raw.unit), text: text(raw.text), isExact: Number.isFinite(raw.exact) }; const exact = Number(value?.quantity ?? value?.amount); return { exact: Number.isFinite(exact) ? exact : null, unit: text(value?.unit), text: null, isExact: Number.isFinite(exact) }; }
function container(value) { const type = text(value?.container?.type ?? value?.container); return { type: CONTAINERS.has(type) ? type : 'carried', display: text(value?.container?.display), placeId: text(value?.container?.placeId) }; }
function assetKey(value, owner) { const c = container(value); return [owner,text(value?.name ?? value?.item),text(value?.ownership) ?? 'unknown',c.type,c.display ?? c.placeId ?? '',quantity(value).unit ?? ''].join('|'); }
export function createCurrentSnapshot() { return { schemaVersion: 1, playerEntityId: 'entity:player', currentTime: null, currentPlace: null, assets: [], currencies: [], entities: {}, relationships: {}, sourceEventIds: [], rebuiltAt: null }; }
export function rebuildCurrentSnapshot(events = [], rebuiltAt = null) { const state = createCurrentSnapshot(); for (const event of events.filter((event) => event?.deletedAt === null && !event.invalid && !NON_MAIN.has(event.timelineContext)).sort(order)) { const value = event.value ?? {}; const owner = text(event.subjectEntityId ?? value.ownerEntityId); if (event.kind === 'story_time' && text(value.time)) state.currentTime = text(value.time); if (event.kind === 'place') { const place = text(value.name ?? value.place); if (place && (!owner || owner === 'entity:player')) state.currentPlace = place; else if (place && owner) state.entities[owner] = { ...(state.entities[owner] ?? { canonicalName: text(value.canonicalName), aliases: [] }), currentLocation: place }; }
 if (event.kind === 'person_state' || event.kind === 'person') { const id = owner; if (id) { const entity = state.entities[id] ?? { canonicalName: text(value.canonicalName ?? value.name), aliases: [], currentLocation: null, durableStatuses: [], transientStates: [] }; const status = text(value.status); if (status) { if (value.stateType === 'transient' || value.transient) entity.transientStates = event.operation === 'clear' || event.operation === 'resolve' ? entity.transientStates.filter((item) => item.label !== status) : [{ label: status, startedByEventId: event.eventId, updatedStoryOrder: source(event) }]; else entity.durableStatuses = event.operation === 'clear' || event.operation === 'resolve' ? entity.durableStatuses.filter((item) => item.label !== status) : [...entity.durableStatuses.filter((item) => item.label !== status), { statusKey: status, label: status, state: 'active', startedByEventId: event.eventId, resolvedByEventId: null, updatedStoryOrder: source(event) }]; } state.entities[id] = entity; } }
 if (event.kind === 'relationship') { const from = owner; const to = text(value.targetEntityId); const dimension = text(value.dimension) ?? 'other'; if (from && to) { const key = `${from}|${to}|${dimension}`; if (event.operation === 'clear') delete state.relationships[key]; else state.relationships[key] = { relationshipId: key, fromEntityId: from, toEntityId: to, dimension, formalStatus: text(value.formalStatus ?? value.value), trend: text(value.trend) ?? 'unknown', label: text(value.label ?? value.value), evidenceEventId: event.eventId, updatedStoryOrder: source(event) }; } }
 if (event.kind === 'inventory' && owner) { const q = quantity(value); const key = assetKey(value, owner); const index = state.assets.findIndex((asset) => asset.assetId === key); const old = index < 0 ? null : state.assets[index]; const next = event.operation === 'set' ? q.exact : (old?.quantity.exact ?? 0) + (['consume','subtract','discard','lose','destroy'].includes(event.operation) ? -(q.exact ?? 0) : (q.exact ?? 0)); const asset = { assetId: key, canonicalName: text(value.name ?? value.item), displayName: text(value.displayName ?? value.name), ownerEntityId: owner, ownership: OWNERSHIP.has(value.ownership) ? value.ownership : 'unknown', container: container(value), quantity: { ...q, exact: q.exact === null ? null : next, isExact: q.exact !== null }, current: next !== 0 || q.exact === null, sourceEventId: event.eventId, updatedStoryOrder: source(event) }; if (index < 0) state.assets.push(asset); else state.assets[index] = asset; }
 if (event.kind === 'currency' && owner) { const name = text(value.name ?? value.currency); const key = `${owner}|${name}|${text(value.unit) ?? ''}`; const index = state.currencies.findIndex((currency) => currency.currencyId === key); const old = index < 0 ? null : state.currencies[index]; const amount = Number(value.amount ?? value.quantity); const next = event.operation === 'set' ? amount : (old?.amount ?? 0) + (event.operation === 'subtract' ? -amount : amount); const currency = { currencyId: key, name, ownerEntityId: owner, amount: Number.isFinite(next) ? next : null, container: container(value), grade: text(value.grade ?? value.tier), current: next !== 0, sourceEventId: event.eventId, updatedStoryOrder: source(event) }; if (index < 0) state.currencies.push(currency); else state.currencies[index] = currency; }
 } state.sourceEventIds = events.filter((event) => event?.deletedAt === null && !event.invalid && !NON_MAIN.has(event.timelineContext) && typeof event.eventId === 'string').map((event) => event.eventId); state.rebuiltAt = rebuiltAt; return state; }
